freshr:
  service:
    name: auth
    serial: 104
  logstash:
    enable: false
  web:
    cors:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - TRACE

server:
  port: 50${freshr.service.serial}
  servlet:
    context-path: /${freshr.service.name}

spring:
  application:
    name: service-${freshr.service.name}

  profiles:
    active: test

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  jackson:
    default-property-inclusion: non_null

  docker:
    compose:
      enabled: false

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: false
        SQL: error
        format_sql: false
        use_sql_comments: false
        type:
          descriptor:
            sql: error
        jdbc:
          batch_size: 5
        default_batch_fetch_size: 1000

  datasource:
    hikari:
      minimumIdle: 200
      maximumPoolSize: 200
      poolName: SpringBootJPAHikariCP
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 580000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    root: error
